name = "emailflow-pro"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "emailflow-pro-db"
database_id = "your-database-id"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"